### ISSUE TITLE
Feature request: aggiungere la pagina "How to be harvested by us"

### ISSUE THREAD

**Issue by aborruso** [italia/dati.gov.it#14]
Il portale europeo espone [questa pagina](https://www.europeandataportal.eu/en/providing-data/how-to-be-harvested-by-us). 

Qualcosa di simile sarebbe opportuna anche nel portale nazionale italiano. Al limite come sezione della pagina sviluppatori.

Grazie

**Comment by giorgialodi** [comment]
Grazie. In effetti è molto utile avere una pagina come quella. Potremmo inserirla nella pagina sviluppatori dell'attuale sito come suggerito. Lo mettiamo in discussione la prossima settimana.

**Comment by giorgialodi** [comment]
@aborruso è stata creata la pagina "Come federare il proprio catalogo con dati.gov.it"  http://www.dati.gov.it/content/come-federare-proprio-catalogo-datigovit Abbiamo però fatto un menu a parte per darne maggiore evidenza.

**Comment by aborruso** [comment]
bene!
