### ISSUE TITLE
La action package_search delle CKAN api non funziona

### ISSUE THREAD

**Issue by cristianolongo** [italia/dati.gov.it#19]
Alla seguente URL ottengo in risposta una pagina HTML che dice 404 page not found

http://www.dati.gov.it/api/3/action/package_search?query=rifiuti

**Comment by marciuz** [comment]
Grazie è già stato affrontato il tema nella issue #1

**Comment by aborruso** [comment]
`rifiuti` è fra l'altro uno di quei package in [lista](http://www.dati.gov.it/api/3/action/package_list), ma che non risponde alla chiamata

    http://www.dati.gov.it/api/3/action/package_show?id=rifiuti

Vedi issue #11
