### ISSUE TITLE
Circa 2000 package restituiscono "Query Error"

### ISSUE THREAD

**Issue by aborruso** [italia/dati.gov.it#21]
Buon pomeriggio,
segnalo che [questi package](https://gist.github.com/aborruso/9b4943af4603e9d639d3ae81e803cbe0) 
 restituiscono `"__type": "Query Error"`. Si tratta di item elencati nella [lista dei package](http://www.dati.gov.it/api/3/action/package_list).

È normale?

Grazie

**Comment by aborruso** [comment]
Buon pomeriggio @marciuz scusami se ti pingo in modo diretto: devo fare altrove questo tipo di segnalazioni? Devo usare un'altra modalità?

Grazie

**Comment by marciuz** [comment]
ciao @aborruso ,
grazie della segnalazione. 

No no, va bene qui, per il futuro meglio un testo descrittivo della issue con un link ad una risorsa esterna di dettaglio (anche un pastebin o gist vanno bene).

**Comment by aborruso** [comment]
Ciao @marciuz e scusa se sono stato un po' grossolano.

Approfitto per circoscrivere a un esempio. Se parto dal [package_list](http://www.dati.gov.it/api/3/action/package_list ), ho 4 risultati correlati:

1. utenti-minori-18-anni-et-dei-servizi-sociali-almeno-prestazione-esterna-quartiere-8
2. utenti-minori-18-anni-et-dei-servizi-sociali-almeno-prestazione-esterna-quartiere-erogazione
3. utenti-minori-18-anni-et-dei-servizi-sociali-almeno-prestazione-esterna-quartiere-3
4. utenti-minori-18-anni-et-dei-servizi-sociali-almeno-prestazione-esterna-quartiere-7

Ma da [query](http://www.dati.gov.it/search/type/dataset?query=Utenti+minori+di+18+anni+di+et%C3%A0+dei+servizi+sociali+con+almeno+una+prestazione+esterna+per+quartiere) con `Utenti minori di 18 anni di età dei servizi sociali con almeno una prestazione esterna per quartiere` ne ottengo due, solo 1 e 4 dell'elenco di sopra.

Grazie

**Comment by giorgialodi** [comment]
Grazie per l'ulteriore dettaglio della segnalazione @aborruso che ha chiarito un po' di più. Lo staff di dati.gov.it sta investigando. Sicuramente il catalogo ha avuto problemi con alcuni dataset duplicati che hanno forse causato questo issue.

**Comment by aborruso** [comment]
Ciao @giorgialodi grazie per il riscontro. 

Sinché il problema dei duplicati o dei puntamenti "problematici" rimane in piedi, sarebbe opportuno inserire quanto prima una nota che ne dia conto, nella parte alta della pagina "Sviluppatori".

Grazie ancora

**Comment by mindrones** [comment]
Per tenere tutte le info qui, si può usare `<details>`:

```
<details>

   - foo
   - bar
   - baz
</details>
```
che rende così:

<details>

   - foo
   - bar
   - baz
</details>

**Comment by aborruso** [comment]
Grazie @mindrones , ma un gist all'esterno spero possa andare bene :)

**Comment by aborruso** [comment]
@giorgialodi @marciuz  ci sono novità in merito alla questione dei duplicati o dei puntamenti "problematici" ?

Grazie

**Comment by giorgialodi** [comment]
@aborruso sui duplicati il team dati.gov.it ci sta lavorando. Metteremo anche un disclaimer come da te suggerito. Appena abbiamo aggiornamenti li comunichiamo attraverso questo canale :)

**Comment by giorgialodi** [comment]
@aborruso come da te suggerito è stato aggiunto un disclaimer. Il problema di questo issue dovrebbe essere risolto. Per quanto riguarda gli altri casi di duplicazioni lo staff sta facendo un'operazione dettagliata per rilevare tutti i casi possibili.

**Comment by aborruso** [comment]
ciao @giorgialodi e @marciuz grazie.

Ho appena rifatto un test parziale (circa i primi 600 item) a partire dal [package_list](http://www.dati.gov.it/api/3/action/package_list)  e [questi package](https://gist.github.com/aborruso/9e623f73511d72e2af9eac0a1a142a6c) mi danno questo tipo di errore se li chiamo con `package_show`:

```
"error": {
"__type": "Not Found Error",
"message": "Not Found"
}
```

Sbaglio qualcosa?

**Comment by giorgialodi** [comment]
@aborruso quest'ultimo issue che sollevi a noi sembra lo stesso issue #11  che è stato già marcato come bug. Stiamo investigando come risolvere il bug.

**Comment by aborruso** [comment]
@giorgialodi hai ragione, il query error di questo thread è risolto ed è diverso da #11 

Grazie, questo lo chiudo
