### ISSUE TITLE
Anomalia su dataset raccolti da Dati.Gov.it:  showcase e harvester insieme ai dataset

### ISSUE THREAD

**Issue by marcomb** [italia/dati.gov.it#23]
Ciao

Ho solo notato ora, facendo alcuni controlli locali tra il nostro catalogo (dati.trentino.it) e Dati.Gov.it, che insieme ai dataset vengono raccolti anche due tipologie di packages che andrebbero filtrate via da parte di chi "harvesta" (localmente non si puo fare).

Purtroppo su Dati.Gov.it attualmente c'è tutto, dataset, showcase, harvester, e non è corretto. 

Il dettaglio un esempio per fare vedere la issue.
Su Dati.Trentino.It abbiamo un dataset delle Botteghe Storiche ed abbiamo nella sezione Showcase anche una webapp che fa vedere un esempio di riuso

Se interrogate via API dati.trentino.it.. (http://dati.trentino.it/api/3/action/package_list), si ottiene una lunga lista di packages, tra cui questi due

"botteghe-storiche-del-trentino",
"botteghe-storiche-trentino",

Però.. uno è uno showcase (type: "showcase")
http://dati.trentino.it/api/3/action/package_show?id=botteghe-storiche-trentino

L'altro è un dataset (type: "dataset")
http://dati.trentino.it/api/3/action/package_show?id=botteghe-storiche-del-trentino

Anche gli harvester (type: "harvest") 
http://dati.trentino.it/api/3/action/package_show?id=pat-siat-geoharvester

Se andate su Dati.Gov.It e cercate "Botteghe Storiche", trovate due dataset, ma uno NON è un dataset.
http://www.dati.gov.it/search/type/dataset?query=Botteghe%20Storiche

E ci sono anche gli harvester, che non sono dataset..
http://www.dati.gov.it/search/type/dataset?query=Harvester

Propongo di intervenire a valle, sul vostro harvester per rimuovere questi "non-dataset", per evitare confusione a chi cerca dataset (che si trovano anche su EDP)

Grazie mille

**Comment by FrancescaGleria** [comment]
Stiamo cercando di sistemare le nostre descrizioni, organizzazione dei data set ecc.  tenendo sotto occhio come  e cosa succede nei passaggi dal nodo  regionale/provinciale  a quello nazionale e a quello EU.  Ci pare possa essere utile come test anche per gli altri per evidenziare qualcosa che potremmo chiamare "lost in harvester" :) or "shift in harvester"

**Comment by giorgialodi** [comment]
Ci stiamo lavorando! Grazie per la segnalazione :)

**Comment by giorgialodi** [comment]
Abbiamo effettuato le necessarie modifiche per far sì che questo non si ripresenti in futuro. Pian piano, con un approccio incrementale, stiamo eliminando il problema per tutti i cataloghi attualmente "harvestati" dal catalogo nazionale. Grazie per la segnalazione!

**Comment by giorgialodi** [comment]
@marcomb @FrancescaGleria issue sistemato :) Ora il catalogo contiene solo oggetti di tipo dataset.
