### ISSUE TITLE
[patenti-guida] campo non spiegato nella metadata

### ISSUE THREAD

**Issue by tamersaadeh** [italia/dati.gov.it#24]
Nel dataset c'è il campo`comune_residenza` (almeno nel `csv` di Piemonte) che non è "spiegato" nella [pdf metadata](http://www.dati.gov.it/dataset/patenti-guida/resource/ab90ff11-c39d-4c6c-98a8-9238f39a9029).

Pagina della dataset:
http://www.dati.gov.it/dataset/patenti-guida

**Comment by giorgialodi** [comment]
Ciao @tamersaadeh, dati.gov.it non entra nei contenuti dei file che sono catalogati. E' appunto un catalogo ed è in grado automaticatimente di raccogliere i metadati attraverso cosiddetti meccanismi di harvesting. Ti consiglio di porre questo tuo quesito/issue direttamente all'amministrazione titolare del dataset o a chi pubblica il dataset  (entrambe informazioni che puoi sapere guardando appunto i metadati che trovi in dati.gov.it). Spero questo possa chiarire il punto che poni.

**Comment by tamersaadeh** [comment]
ok, grazie!
