### ISSUE TITLE
Uniformare formati dati

### ISSUE THREAD

**Issue by ddavidebor** [italia/dati.gov.it#26]
Noto che i formati dei dati sono misti: xml, csv, etc etc a seconda della fonte.

Perchè i dati siano realmente fruibili è necessario che il lavoro di ETL venga svolto da dati.gov.it e che i dati vengano esposti in formati multipli:

- csv, excel
- json
- xml
- api

Il mio suggerimento è usare il json come formato intermedio, per via dell'efficienza degli strumenti di serializzazione disponibili e del numero di librerie per poi convertirli in altri formati.

Inoltre è facile usare il json per rappresentare dati tabulari, decisamente impratico il contrario.

Davide

**Comment by giorgialodi** [comment]
Ciao Davide, il catalogo dati.gov.it è un catalogo di **metadati** che non entra nel merito dei dati stessi detenuti dalle PA titolari, responsabili della pulizia e della pubblicazione secondo diversi formati. Attraverso linee guida nazionali cerchiamo di indirizzare il lavoro delle PA, anche rispetto a principi che qui auspichi. Nell'ambito del progetto Data & Analytics Framework (DAF), dove confluiscono anche dati e non solo metadati, operazioni di ETL potrebbero essere possibili. Ti invito pertanto a seguire quel progetto (trovi su github italia diversi repository riguardanti il DAF)
