### ISSUE TITLE
Sostituzione email info@agid in privacy policy 

### ISSUE THREAD

**Issue by danielaiozzo** [italia/dati.gov.it#27]
Ciao, poichè la mail info@agid.gov.it sta per essere disabilitata, andrebbe sostitutita con protocollo@pec.agid.gov.it in questa pagina
https://www.dati.gov.it/content/privacy-policy
Grazie

**Comment by giorgialodi** [comment]
Ciao @danielaiozzo, informo subito della cosa. Grazie!

**Comment by danielaiozzo** [comment]
Grazie mille @giorgialodi

**Comment by giorgialodi** [comment]
Sostituita! https://www.dati.gov.it/content/privacy-policy
Ciao
