### ISSUE TITLE
pagina sviluppatori: URL verso pagina che non esiste

### ISSUE THREAD

**Issue by aborruso** [italia/dati.gov.it#28]
In [questa pagina](https://www.dati.gov.it/content/sviluppatori)  in corrispondenza di "documentazione di DKAN" c'è un URL verso una pagina che non esiste.

**Comment by giorgialodi** [comment]
@aborruso  Dovrebbe essere ok ora. Grazie per la segnalazione!

**Comment by aborruso** [comment]
@giorgialodi grazie a te
