### ISSUE TITLE
Alcuni errori http nell'elenco dei cataloghi sorgente

### ISSUE THREAD

**Issue by aborruso** [italia/dati.gov.it#30]
Li incollo sotto.

Saluti

```
http: error: ConnectionError: HTTPConnectionPool(host='156.54.180.186', port=80): Max retries exceeded with url: /ckan/organization/datasets/camera-di-commercio-di-macerata (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f33ba380358>: Failed to establish a new connection: [Errno 111] Connection refused',)) while doing POST request to URL: http://156.54.180.186/ckan/organization/datasets/camera-di-commercio-di-macerata

http: error: ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',)) while doing POST request to URL: http://www.salentojonico.it/api/3/action/package_list

http: error: ConnectionError: HTTPConnectionPool(host='dati.comune.francavillafontana.br.it', port=80): Max retries exceeded with url: /api/3/action/package_list (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd115f303c8>: Failed to establish a new connection: [Errno 111] Connection refused',)) while doing POST request to URL: http://dati.comune.francavillafontana.br.it/api/3/action/package_list

http: error: ConnectionError: HTTPConnectionPool(host='dati.comune.latiano.br.it', port=80): Max retries exceeded with url: /api/3/action/package_list (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f83156b03c8>: Failed to establish a new connection: [Errno 111] Connection refused',)) while doing POST request to URL: http://dati.comune.latiano.br.it/api/3/action/package_list

http: error: ConnectionError: HTTPConnectionPool(host='www.terradellegravine.eu', port=3389): Max retries exceeded with url: /api/3/action/package_list (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8c71fc03c8>: Failed to establish a new connection: [Errno 111] Connection refused',)) while doing POST request to URL: http://www.terradellegravine.eu:3389/api/3/action/package_list
```

**Comment by giorgialodi** [comment]
Ciao Andrea,
la prima sorgente non è più disponibile. Era una cosa volutamente temporanea. Ciò significa che in dati.gov.it ci sono dataset non più aggiornati per quella sorgente, sebbene ne siano presenti alcuni. La lista dell'elenco delle sorgenti mostra infatti 0 dataset dalle attività di harvesting. 
Le altre sorgenti in effetti non funzionano. Penso sia una cosa temporanea ma bisogna contattarli.  Grazie, come sempre, per la segnalazione.

**Comment by aborruso** [comment]
Ciao Giorgia,

> la prima sorgente non è più disponibile. Era una cosa volutamente temporanea. 

non era indicato e quindi l'ho messa insieme alle altre, perdonami se ho fatto confusione. 
Forse una nota, per le sorgenti diverse dalle altre, potrebbe essere utile.

Grazie a te

**Comment by giorgialodi** [comment]
Andrea,
mi è stato appena segnalato su altro canale che le sorgenti di cui sopra sembrano ospitate su cloud  attualmente non raggiungibile. Sembra quindi un problema temporaneo delle sorgenti e non di dati.gov.it

**Comment by aborruso** [comment]
Giorgia allora lascerei aperta la issue. Faccio un test la settimana prossima e nel caso chiudo.


Grazie

**Comment by giorgialodi** [comment]
Va bene Andrea

**Comment by aborruso** [comment]
Ciao @giorgialodi ,
fatto test adesso: rimangono soltanto errori per openexpo2015 e "Camera di Commercio di Macerata", che immagino siano da rimuovere dalla lista (o in alternativa mettere una nota), perché non più attivi.

Buona giornata

**Comment by giorgialodi** [comment]
Ciao Andrea,

sì questa tua proposta è stata inoltrata al team di coordinamento e sviluppo di dati.gov.it.
Grazie mille come sempre!

**Comment by giorgialodi** [comment]
Ciao Andrea,

il team di sviluppo e coordinamento di dati.gov.it provvederà a rimuovere i cataloghi (temporanei e non più funzionanti) dalla lista.

**Comment by aborruso** [comment]
@giorgialodi grazie!

Lascerei a voi la chiusura della issue, non appena il team di sviluppo e coordinamento di dati.gov.it rimuoverà i cataloghi

**Comment by giorgialodi** [comment]
Ciao @aborruso, 
le due sorgenti che davano errori openexpo2015 e "Camera di Commercio di Macerata" sono state eliminate dalla lista come puoi anche tu verificare qui: https://www.dati.gov.it/elenco-harvest-sources Chiuderei l'issue. 
Ciao e grazie!

**Comment by aborruso** [comment]
@giorgialodi grazie per la segnalazione e grazie a chi se ne è occupato.
