### ISSUE TITLE
Feature request: inserire nel single page, l'URL originale del dataset

### ISSUE THREAD

**Issue by aborruso** [italia/dati.gov.it#33]
Buongiorno,
sarebbe molto comodo che nella single page di un dataset (come [questo](https://www.dati.gov.it/dataset/simon-elenco-progetti-relativo-allasse-vi-assistenza-tecnica-fse-por-regione-lazio)), ci fosse anche l'URL dello stesso dataset nel catalogo sorgente.

Si potrebbe inserire l'href `http://dati.lazio.it/catalog/dataset/abafa688-9ce4-4670-9a5d-8e215eaf7f8a` in corrispondenza del suo identificativo.

Grazie

![image](https://user-images.githubusercontent.com/30607/53876074-50bc2600-4006-11e9-9c43-96b6d055403b.png)

**Comment by giorgialodi** [comment]
Ciao @aborruso, 
grazie mille per la proposta di miglioramento. Secondo il nuovo piano triennale appena pubblicato da AgID è prevista un’evoluzione di dati.gov.it. In merito, le persone coinvolte nell'evoluzione stanno radunando tutti i commenti e le problematiche che vengono segnalate dalle comunità che riutilizzano e accedono a dati.gov.it (incluso questo commento) per la loro implementazione nell'evoluzione.

**Comment by aborruso** [comment]
Ciao @giorgialodi grazie.
Allora la chiudo e rimane in `enhancement`.

Ne approfitto per quella che per ora è una suggestione: visto che si sta "ripartendo", si potrebbe immagine di lanciare "ufficialmente" una raccolta di feature request a tema per aziende, consulenti, cittadini, ONG, PA, ecc..

**Comment by giorgialodi** [comment]
A me sembra una bella idea. Grazie mille per il suggerimento! Mi faccio portavoce di questa cosa con tutti i gruppi che lavorano sui dati aperti e sui cataloghi :)
