### ISSUE TITLE
dataset nascosto, comunque visibile

### ISSUE THREAD

**Issue by aborruso** [italia/dati.gov.it#34]
Buongiorno,
segnalo che c'è un dataset non pubblico, che è comunque visibile:

- via API https://www.dati.gov.it/api/3/action/package_show?id=33bb1acf-468f-478b-8803-9a7cb461f158
- via visualizzazione di gruppo https://www.dati.gov.it/group/apb-abt-grundbuch-und-kataster

Grazie

**Comment by giorgialodi** [comment]
Ciao @aborruso, grazie come sempre. Il team è informato e sta investigando.

**Comment by giorgialodi** [comment]
Ciao @aborruso, il team di sviluppo di dati.gov.it ha rimosso il dataset e terranno sotto osservazione la sorgente dati per successivi harvesting.  Dati.gov.it è in fase di revisione; un approccio al problema più sistematico sarà valutato in quella sede

**Comment by aborruso** [comment]
Vi ringrazio
