### ISSUE TITLE
Front-end DKAN è già una scelta di progetto?

### ISSUE THREAD

**Issue by ghost** [italia/dati.gov.it#5]
Se sì, perché utilizzarlo invece di CKAN? Almeno, così ho inteso.

Approfitto di questo spazio perché finora mi sembra l'unico dove interagire in merito.
Grazie e ben felice di poter collaborare!

**Comment by giorgialodi** [comment]
La scelta di DKAN è stata fatta già nella precedente riorganizzazione del catalogo dei dati aperti (2015) ed è attualmente la piattaforma in uso per il catalogo disponibile online. Nell'evoluzione del catalogo stesso si prevede di passare gradualmente a un CKAN come backend rendendo possibile un decoupling tra il backend e il front-end. Suggerisco a tal proposito di vedere il documento di evoluzione, dove l'architettura complessiva è descritta in maggior dettaglio.
