### ISSUE TITLE
Feature request: aggiungere il codice IPA

### ISSUE THREAD

**Issue by aborruso** [italia/dati.gov.it#7]
Se si estendesse l'anagrafica delle PA inserite in catalogo, con il codice [IPA](http://www.indicepa.gov.it/documentale/n-opendata.php), si arricchirebbe molto quanto esposto in termini di Linked Data e in generale di identificazione automatica della source.

Grazie

**Comment by giorgialodi** [comment]
Nel profilo DCAT-AP_IT il codice IPA è già previsto, tanto che le amministrazioni che si stanno gradualmente adattando al profilo, includono tale metadato (è rappresentato da un valore stringa-campo "identifier" dell'organizzazione). Qui intendi che vorresti visualizzare questo dato nella landing page del dataset in corrispondenza del ruolo dell'amministrazione rispetto al dataset? 
Il discorso che poni invece sul lato LinkedData mi sembra più articolato, se ho inteso bene. Vorresti avere un URI univoco che usi il codice IPA per identificare univocamente le amministrazioni a livello nazionale? Se sì, segnalo che già uno sforzo è stato fatto in passato da AgID con il progetto SPCData. Per esempio questa è l'amministrazione AgID: http://spcdata.digitpa.gov.it/browse/page/Amministrazione/agid. L'URI in effetti usa il codice IPA, come noti. Il progetto è attualmente non aggiornato. L'idea è quella di riprendere in mano tutto, modellando le organizzazioni secondo i nuovi modelli Europei che nel frattempo sono nati. Stiamo lavorando proprio su questo ora con alcune PA.

**Comment by aborruso** [comment]
Ciao @giorgialodi , 
lo domandavo basandomi sulle risultanze delle query sulle API, che non mi restituivano codici IPA. 
Ok, quindi in ogni caso è previsto.
Con il sito giù non riesco a recuperare da nessuna parte il PDF del profilo DCAT-AP_IT, volevo capire se fosse obbligatorio.

Avrebbe molto senso che lo fosse, una PA senza IPA è un po' come una persona senza CF. 

Grazie

**Comment by giorgialodi** [comment]
Il codice IPA è previsto e obbligatorio. A breve mettiamo online in "read the docs" una linea guida navigabile con tutte le proprietà e le classi del profilo e i vari mapping. Sarà quindi più facile, si spera, poter capire come metadatare secondo il profilo nazionale.

**Comment by aborruso** [comment]
Ok grazie @giorgialodi.

L'obbligatorietà DCAT-AP_IT è già in essere nel nuovo portale, o sono anche mappate organizzazioni che non rispettano ancora il DCAT-AP_IT?

Avevo intravisto la [guida in costruzione](http://guida-pratica-dcat-ap-it.readthedocs.io/en/latest/) cercando copia del PDF con le specifiche. Bene!

**Comment by giorgialodi** [comment]
Ci sono mappate anche organizzazioni che non rispettano ancora il profilo. La guida che citi sarà presto sostituita con quella completa, con tutti gli hyperlink e con la possibilità di scaricarla anche in PDF.

**Comment by aborruso** [comment]
Aggiungo un corollario correlato a #1 : se capisco bene per leggere il codice IPA di un'organizzazione bisognerà fare una richiesta di [organization_show](http://docs.ckan.org/en/latest/api/#ckan.logic.action.get.organization_show).

Questa del codice IPA è una ragione in più per abilitare presto anche questo tipo di richieste.

Grazie
