### ISSUE TITLE
Feature request: rendere disponibile un validatore DCAT-AP_IT

### ISSUE THREAD

**Issue by aborruso** [italia/dati.gov.it#8]
Nella pagina dedicata agli sviluppatori ci vorrebbe il link a un validatore (immagino ci sia).

Grazie

**Comment by giorgialodi** [comment]
Lo sviluppo di un validatore DCAT-AP_IT è già pianificato e già avviato (al momento in modalità best effort). A iniziare, l'idea è di quella di partire dal validatore europeo che sfrutta query SPARQL per verificare la presenza di tutti i metadati come richiesto dal profilo (validatore quindi più sintattico). Il primo draft del validatore accetterà in input solo file RDF (nelle tre tipiche serializzazioni, JSON-LD, RDF/XML e RDF/turtle). Nell'evoluzione del catalogo nazionale, la validazione sarà probabilmente più articolata; tuttavia, quest'ultima è ancora da costruire.

**Comment by aborruso** [comment]
@giorgialodi ma al momento, quando inserite una nuova fonte per fare harvesting, fate una validazione "solo" `DCAT-AP`, che poi viene in qualche modo rimappata `DCAT-AP_IT`?

Grazie

**Comment by marciuz** [comment]
ciao @aborruso 
al momento sulla versione attuale non abbiamo un validatore in senso stretto, ma un sistema di *quality improvement* che analizza i metadati ed i dati dei cataloghi e fornisce un log dettagliato ad uso del gestore del catalogo. Si può considerare (anche) come una "pre-validazione" propedeutica al passaggio a DCAT-AP_IT. Non c'è ancora una documentazione pubblica di questo strumento, ma è nostra intenzione pubblicare un draft aperto ai commenti.

**Comment by aborruso** [comment]
@marciuz grazie.

E i dati del gestore del catalogo, a valle del _quality improvement_, vanno online quando sono full compliant  DCAT-AP_IT?

**Comment by marciuz** [comment]
No, allo stato attuale il sistema effettua uno "skip" del record solo in casi estremi (ad es. mancanza di distribuzioni o *resources* - nel linguaggio CKAN , cioè i file o le api collegati).
Nel tempo le policy diverranno ragionevolmente più restrittive fino ad adeguarsi a DCAT-AP_IT ed ai suoi vincoli, per cui un dataset che non abbia dei campi dichiarati obbligatori (1...N o 1) non sarà importato. E' tuttavia importante predisporre un sistema efficace di feedback. Si sta lavorando (anche) a questo.

**Comment by imuttley** [comment]
Saluti, ho creato un semplice programma in python per la validazione in *locale* di un file **.rdf** del DCAT_AP su mio repository [imuttley](https://github.com/imuttley/opendata_workspace)    
Il **validator.py** *nomefile.rdf* esegue le *rules-[0-9]+.sparql* e restituisce il risultato su *cli*.
Le query *sparql* le ho ricavate dal validatore DCAT-AP fornito ufficialmente dal [portale europeo](https://joinup.ec.europa.eu/catalogue/distribution/dcat-ap-validator-110).
Stavo adesso eseguendo dei test per quanto riguarda il vocabolario DCAT_AP-it, ma riesco ad accedere al risorsa solo in http, generando degli errori. L'URI per il **DCATAPIT** in *https://dati.gov.it/onto/dcatapit#* è corretto ?

**Comment by giorgialodi** [comment]
L'IRI corretto è http://dati.gov.it/onto/dcatapit

**Comment by giorgialodi** [comment]
Il validatore è stato costruito (potete riferirvi a questo: https://github.com/italia/daf-semantics/tree/master/semantic_validator)
